### ISSUE TITLE
google.pubsub.v1.Publisher.Publish gets 404

### ISSUE THREAD

**Issue by aug70** [GoogleCloudPlatform/pubsub#123]
This repo may not be right place to report this but I'm trying to deploy a very simple Spring Boot app to GCP. It's failing on deploy and I see a lot of 404 errors. See find details in this [Stack Overflow ticket](https://stackoverflow.com/questions/46302785/google-pubsub-v1-publisher-publish-gets-404) Please advise.

**Comment by kamalaboulhosn** [comment]
You would need to report this to the writers of the code that actually publishes to Google Cloud Pub/Sub. I expect that the topic does not exist that the Publisher is trying to publish to. It is possible this doesn't actually cause an issue with deployment (perhaps the failure only results in events not being published to Cloud Pub/Sub, but otherwise proceeds as expected) and that the issue is elsewhere. This looks more like an issue with app engine deployment than Pub/Sub, so unfortunately there is nothing we can investigate in this inside this repo.

**Comment by aug70** [comment]
I have reported it in [here](https://github.com/GoogleCloudPlatform/pubsub/issues/123). But please let me know if you think there's another place that I can report this. Thanks for your answer.
