### ISSUE TITLE
Connector shadow jar is too fat

### ISSUE THREAD

**Issue by mkuthan** [GoogleCloudPlatform/pubsub#252]
Connector shadow jar contains Kafka libraries - current version is 2.6.0. When the connector is on Kafka Connect classpath there is a libraries conflict. Even if the Kafka Connect cluster is build and configured using Kafka version 2.5.1, with installed PubSub connector you will get Kafka Cluster 2.6.0 effectively. 

See (Note, however, that the archive should never include the Kafka Connect API or runtime libraries):
https://docs.confluent.io/platform/current/connect/devguide.html#creating-an-archive

**Comment by kamalaboulhosn** [comment]
Does this manifest itself as an error? I'm trying to understand how to see the issue and test any changes.

**Comment by mkuthan** [comment]
Just setup Kafka Connect cluster using distribution version != 2.6.0. Then put the Pubsub connector on the class path and restart the cluster. You will get cluster version 2.6.0 (according to the logs).

**Comment by dpcollins-google** [comment]
So, it looks like we've specified the connect API as provided by the cluster https://github.com/GoogleCloudPlatform/pubsub/blob/445171449f0031bf26b6d183e9fbff66021b195c/kafka-connector/pom.xml#L74. It is possible that Kafka Connect delegates to the kafka client library to determine its version? The kafka client library added a new "enforceRebalance" API in v2.6.0 https://kafka.apache.org/26/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#enforceRebalance-- which the Pub/Sub Lite kafka shim overrides. Does it cause breakages? Or does it just report version 2.6.0?

**Comment by mkuthan** [comment]
I would not define Kafka clients dependency at all. This is a transitive dependency of Kafka Connect API:
https://mvnrepository.com/artifact/org.apache.kafka/connect-api/2.6.0

**Comment by dpcollins-google** [comment]
It is also a transitive dependency of the Pub/Sub Lite adapter used in the Source connector. And because they added a new API to Consumer in 2.6, it is currently overridden. I could make it not @Override, but I'm still failing to see what issue this is causing other than different cluster logging. Does this prevent other connectors from working properly?

**Comment by mkuthan** [comment]
When I configure Kafka Connect cluster using version X, I would expect version X at runtime regardless of installed connectors. If the connector is not compatible with the installed cluster version I would expect errors during startup, but I got upgraded cluster :(

As long as Kafka libraries are backward compatible is not a big deal but it could be dangerous. Let's assume the situation when my 2.5.1 cluster is configured using deprecated configuration property. If the property is removed in version 2.6.0 the connector bundled with Kafka 2.6.0 libraries will break my cluster.

**Comment by dpcollins-google** [comment]
> I would expect version X at runtime regardless of installed connectors

I would expect this too. That's not my point. The point I'm trying to make is: I think you are still getting version 2.5.1 at runtime. The pubsub connector jar does bundle a copy of Kafka Connect, just the kafka client. My theory is that Kafka Connect improperly assumes that its version is the same as the version of the kafka client its using, rather than testing its own version. This would explain why you get logging that the version is 2.6.0 even when the version is actually 2.5.1.

**Comment by mkuthan** [comment]
Hmm, interesting - I have to check logs again and I'm going to ask on Kafka mailing list as well. Maybe it is totally fine to have customised Kafka clients versions for every connector (connector classpaths are isolated).  Strange assumption indeed, classloaders are hierarchical, so everything from Kafka Connect lib directory should take precedence over libs from connector package. But who knows? It is also fully possible that classes are loaded in alphabetical order of jar filenames. I used to deploy many apps on J2EE servers many years ago (and Hadoop apps not so many years ago) and classpath hell was very common issue, so I would avoid libraries duplication on classpath at first.

How did you verify that effective Kafka client version is from Kafka Connect but not from connector?

**Comment by dpcollins-google** [comment]
> I have to check logs again

If you have an exact log line, I might better know what I'm looking for? I
tried crawling the connector source to confirm, but the structure of the
particular log line would help.

> How did you verify that effective Kafka client version is from Kafka
Connect but not from connector?

You can verify that the connector library is "<provided>" in our pom.xml
file as linked above. Its entirely possible that my maven understanding is
lacking, I would be very surprised if `mvn package` shipped a version of
the connector along with the jar. I would not be surprised if it shipped a
version of the kafka client along with the jar however, since we explicitly
ask it to. Hence my hypothesis that the connector is delegating to the
client in some way for printing this log line.

> Strange assumption indeed, classloaders are hierarchical, so everything
from Kafka Connect lib directory should take precedence over libs from
connector package

I was actually assuming something more basic: that it was calling a common
utility or logging method from the kafka client to attach the version to
the log message. It would help to know exactly where the log line in
question is generated in the Kafka Connect code to validate/disprove this
hypothesis.

I can try adding shading relocation of the kafka client to prevent this
issue? I'm just not as sure that it is an actual issue, nor do I have a
good way of determining if shading would cause the log lines to print the
correct results without knowing what the log lines are and under what
scenario they are generated.
